version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    container_name: app_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app_test
    depends_on:
      postgres_test:
        condition: service_healthy
    environment:
      - DB_HOST=postgres_test
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=testdb
    volumes:
      - .:/app
      - go_test_modules:/go/pkg/mod

volumes:
  postgres_test_data:
  go_test_modules: 