apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-clean-template.fullname" . }}-config
  labels:
    {{- include "go-clean-template.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }} 